# -*- coding: utf-8 -*-
"""Copia de Lab5. Programming Paradigms Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ea8vDJcg-Yzo-rjGJ9h5jz5uzrqpgFF

# Lab5. Programming Paradigms Comparison

**Student Name:** Peña Rodriguez Jennifer   
**Group:** 3A______________________________________  
**Date:** 20/05/26_______________________________________  

---

# Objective

You will solve the same problem using different programming paradigms.

The goal is to understand how the way you think and structure a solution changes depending on the paradigm.



# Required Paradigms

You must implement the solution using ALL of the following paradigms:

1. Imperative Programming  
2. Structured Programming (functions + control structures)  
3. Modular Programming  
4. Object-Oriented Programming (OOP)  
5. Functional Programming (basic level)


# Important Rules

- The SAME problem must be used in all paradigms.
- You must NOT copy-paste the same solution with small changes.
- Each paradigm must show a different way of structuring the solution.
- Each section must include:
  - explanation in your own words
  - working code
  - a personal modification
  - a short reflection


# Problem Description

Describe the problem you will solve:

```text
A system that calculates the average grade of students and determines if they pass or fail.

# 1. 1. Imperative Programming  

## Brief Explanation
It's a paradigm to work step by step instructions using variables and loops.


## Code Example
Complete the steps:
"""

# Given data
grades = [70, 80, 90]
total = 0
# 1. Calculate sum using a loop
for i in grades:
  total += i
average = total / len(grades)

if average >= 70:
  print("pass")
else:
  print("fail")

print("Average: ", average)

"""## Your Modification
What did you change and why?

Example: I added a function to calculate the highest grade and printed it together with the average.


## Reflection
What did you learn from this approach and how does it compare to others?

## 2. Structured Programming (functions + control structures)


##Brief Explanation
Organizes code into named functions with clear control flow, separating concerns into reusable blocks

##Code
"""

def calculate_average(grades):
  total=0
  for grade in grades:
    total+=grade
    return total/len(grades)
  def determine_status(average):
    if average>=70:
     return "pass"
    else:
      return "fail"
  def print_results(average,status):
    print("Average:", average)
    print("Status:", status)

    grades=[70,80,90]
    average=calculate_average(grades)
    status=determine_status(average)
    print_results(average,status)

"""##Your modification:
Added a print_results function to separate output logic from calculations.

##Reflection:
Unlike imperative programming, structured programming breaks the problem into fuctions, making code easier read,test and reuse independently.

##3. Modular Programming
##Brief explanation:
Divides the program into independt modules, each responsible for a specific task, simulating separate files/namespaces
"""

# --Module:grades_calculator --
def mod_calculate_average(grades):
  return sum(grades)/len(grades)

def mod_get_highest(grades):
  return max(grades)


def mod_get_lowest(grades):
  return min(grades)

  # -- Module: evaluator --
  def mod_evaluate(average)
    if average>=70:
      return "pass"
    else:
      return "fail"

    # -- Module: reporter --
    def mod_print_results(grades, average, status):
      print("Grades:", grades)
      print("Highest:", mod_get_highest(grades))
      print("Lowest:", mod_get_lowest(grades))
      print("Average:", average)
      print("Status:", status)

    # -- Main program --
    grades=[70,80,90]
    average=mod_calculate_average(grades)
    status=mod_evaluate(average)
    mod_print_results(grades,average,status)

"""##Your modification:
Added modules to also report the highest and lowest grades, showing how modules can be extended independently.

##Reflection:
 Modular programming goes further than structures by grouping related functions into logical units. Each module can be developed or changed without affecting others.

##4. Object-Oriented Programming (OOP)
##Brief Explanation:
Models the problem as objects with attributes (data) and methods (behavior), using classes as blueprints.
"""

class Student:
  def __init__(self, name, grades):
    self.name=name
    self.grades=grades

  def calculate_average(self):
    return sum(self.grades)/len(self.grades)

  def calculate_average(self):
    return sum(self.grades)/len(self.grades)

    def get_status(self):
      if self.calculate_average()>=70:
        return "pass"
      else:
        return "fail"

      def report(self):
        avg = self.calculate.average()
        status = self.get_status()
        print(f"Student: {self.name}")
        print(f"Grades: {self.grades}")
        print(f"Average: {avg}")
        print(f"Status: {status}")


student1= Student("Jennifer",[70,80,90])
student1.report()

"""##Your modification:
Created a student class that bundless the student's name with their grades, making it easy to handle multiple students as objects.

##Reflection:
OOP encapsulates data and behavior together. Unlike the previous paradigms, you can now create multiple student instances without repeating logic.

##5.Functional Programming

##Brief Explanation:
Treats computation as the evaluation of mathematical functions, avoiding changing state and using functions like map, filter and reduce.
"""

from logging import getHandlerNames
from functools import reduce
grades=[70,80,90]

total=reduce(lambda acc, g: acc+ g, grades,0)
average= total/len(grades)

get_status= lambda avg: "pass" if avg >=70 else "fail"

individual_status=list(map(lambda g:(g, "pass" if g >=70 else "fail"),grades))

print("Average:", average)
print("Status:", get_status(average))
print("Individual Status:", individual_status)

"""##Your modification:
Added map to evaluate each individual grade's pass/fail status, showing functional chaining on collections.

##Reflection:
Functional programming avoids variables that change over time. Instead of loops with total +=i, we use reduce. The code is more declarative.
"""